version: '3.1'

services:
    database:
        image: 'postgres:14'
        restart: always
        environment:
            POSTGRES_DB: 'speackTock'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: '7es@Fsf54ds!'
        ports:
            - '5444:5432'
        volumes:
            - database-data:/var/lib/postgresql/data/
volumes:
    database-data:
